version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mon_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: insurance_platform
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - reseau_mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mon_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - reseau_mysql

volumes:
  mysql_data:

networks:
  reseau_mysql:
